import { Difficulty } from './enums/difficulty';

export const HIKES = [
  {
    id: 1,
    name: 'Eze et le Mont Bastide par le sentier Frédéric Nietzsche',
    distance: 6.35,
    startPoint: "Gare SNCF d'Eze-Bord-de-Mer",
    endPoint: "Gare SNCF d'Eze-Bord-de-Mer",
    estimatedTime: 3.15,
    difficulty: Difficulty.EASY,
    scheduledDate: new Date(2025, 0, 20),
    elevation: 592,
    done: true,
    actualTime: 6,
    score: 5,
  },
  {
    id: 2,
    name: 'Tour de la Napoule',
    distance: 6.37,
    startPoint: 'Port de la Rague',
    endPoint: 'Le Château de la Napoule',
    estimatedTime: 4.5,
    difficulty: Difficulty.EASY,
    scheduledDate: new Date(2026, 2, 15),
    elevation: 130,
    done: false,
  },
  {
    id: 3,
    name: 'Tour de Ile Sainte Marguerite',
    distance: 7.5,
    startPoint: 'Débarcadère',
    endPoint: 'Débarcadère, Cannes',
    estimatedTime: 2,
    difficulty: Difficulty.EASY,
    scheduledDate: new Date(2026, 2, 15),
    elevation: 30,
    done: false,
  },
  {
    id: 4,
    name: 'Tour de Saint Jean-Cap-Ferrat',
    distance: 13.4,
    startPoint: 'Villa Kerylos (Beaulieu-sur-Mer)',
    endPoint: 'Gare de Villefranche sur Mer',
    estimatedTime: 4.5,
    difficulty: Difficulty.AVERAGE,
    scheduledDate: new Date(2025, 9, 15),
    elevation: 123,
    done: true,
    actualTime: 6.5,
    score: 5,
  },
];
